### ISSUE TITLE
Whacky expansion of HTML inside template string

### ISSUE THREAD

**Issue by stevage** [ctf0/vscode-auto-expand-on-enter#1]
I had this code in some JavaScript inside an HTML file:

```
template.innerHTML = `<div class="mapboxgl-ctrl mapboxgl-ctrl-group">
            <div class="search">
              <input id="geocode-input" type="text" size="50" /><button id="geocode-button">Geocode</button>
            </div>
          `
```

I maneuver the cursor after `"50 />` (before the `<button` and press enter. The cursor jumps way above the code, and a second cursor appears way below. Totally whacky.

**Comment by ctf0** [comment]
u r correct, the emmet `balanceOut` cmnd sometimes gives incorrect positions, its on my todo list.

**Comment by ctf0** [comment]
after some testing, currently the only solution i can think of is either use `regex < not good` or a `parser < recommended`

but as i dont know how to implement an html parser and get the correct data out of it then probably will go with `regex` which might have some down sides.

if you can help with any plz advice, thanx.

**Comment by ctf0** [comment]
@stevage check the latest release and reply back if u still have issues.
